steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/pavan-bommideni/Spring-boot-graphql']
- name: 'gcr.io/cloud-builders/mvn'
  args: ['package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/deft-landing-244816/spring:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/deft-landing-244816/spring:latest']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'graphql', '--image', 'gcr.io/deft-landing-244816/spring:latest', '--cluster', 'standard-cluster-1', '--cluster-location', 'us-central1-a', '--platform', 'gke', '--namespace', 'default', '--quiet']

